services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8501:8501"
    labels:
      - autoheal=true
    # Healthcheck inherited from Dockerfile; override here if you need different timing.

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app
